//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pickpoints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pickpoints()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PickpointId { get; set; }
        public int PickpointIndexId { get; set; }
        public int PickpointCityId { get; set; }
        public int PickpointStreetId { get; set; }
        public Nullable<int> PickpointHouseNumber { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Indexes Indexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Streets Streets { get; set; }
    }
}
