//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ProductId { get; set; }
        public int ProductUnitId { get; set; }
        public string ProductArticleNumber { get; set; }
        public int ProductNameId { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductSaleMax { get; set; }
        public int ProductFactoryId { get; set; }
        public int ProductImporterId { get; set; }
        public int ProductCategoryId { get; set; }
        public Nullable<byte> ProductSale { get; set; }
        public int ProductCount { get; set; }
        public string ProductDescription { get; set; }
        public string NameOfImage { get; set; }
        public byte[] ProductImage { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Facroties Facroties { get; set; }
        public virtual Importers Importers { get; set; }
        public virtual Names Names { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Units Units { get; set; }
    }
}
